"""subadmin

迁移 ID: 33892c04d7ce
父迁移: afb5fc69c91d
创建时间: 2025-07-04 17:30:33.373375

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "33892c04d7ce"
down_revision: str | Sequence[str] | None = "afb5fc69c91d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_admins", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.drop_column("sub_admins")

    # ### end Alembic commands ###
