"""bad_words

迁移 ID: db8dc5bd6c94
父迁移: bfe784d0886d
创建时间: 2025-09-21 16:52:55.574813

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "db8dc5bd6c94"
down_revision: str | Sequence[str] | None = "bfe784d0886d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("badwords_check", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("custom_badwords", sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.drop_column("custom_badwords")
        batch_op.drop_column("badwords_check")

    # ### end Alembic commands ###
