"""fix_list_and_types

迁移 ID: ecfd8a463513
父迁移: f65219e033c6
创建时间: 2025-07-08 21:06:58.195400

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "ecfd8a463513"
down_revision: str | Sequence[str] | None = "f65219e033c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_admin_list", sa.JSON(), nullable=False))
        batch_op.drop_column("sub_admins")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sub_admins",
                sqlite.JSON(),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.drop_column("sub_admin_list")

    # ### end Alembic commands ###
