"""remove_unused

迁移 ID: f290a4c57bc3
父迁移: db8dc5bd6c94
创建时间: 2025-09-22 12:54:58.577117

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "f290a4c57bc3"
down_revision: str | Sequence[str] | None = "db8dc5bd6c94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.drop_column("nailong")
        batch_op.drop_column("judge")
        batch_op.drop_column("anti_recall")
        batch_op.drop_column("anti_spam")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anti_spam", sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column("anti_recall", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("judge", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("nailong", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
