name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 指定触发分支
    paths:
      - '**'    # 监控所有文件变更（可按需调整）

jobs:
  runTest:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set environment
        run: uv sync

      - name: Load test
        run: |
          uv run run-test.py

