name: PullRequest CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"

jobs:
  runTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整提交历史
          ref: ${{ github.event.pull_request.head.sha }} # 明确指定PR分支的SHA

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: |
            .venv
            uv.cache
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set environment
        run: |
          uv venv
          uv sync

      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
            packages: nmap
            version: 1.0


      - name: Get Python path
        run: |
          PYTHON_BIN="$(uv run python -c 'import sys; print(sys.executable)')"
          echo "PYTHON_BIN=$PYTHON_BIN" >> $GITHUB_ENV

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          python-path: ${{ env.PYTHON_BIN }}
          pylance-version: latest-release

      - name: Load test
        run: |
          uv run run-test.py
